on:
  pull_request:
  push:
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: rolling
      - name: Add more dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ros-rolling-diagnostic-updater
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: rolling
